[package]
name = "test_coprocessor"
version = "0.0.1"
edition = "2018"
publish = false

[features]
protobuf-codec = [
  "kvproto/protobuf-codec",
  "test_storage/protobuf-codec",
  "tidb_query/protobuf-codec",
  "tikv/protobuf-codec",
  "tipb/protobuf-codec",
  "txn_types/protobuf-codec",
]
prost-codec = [
  "kvproto/prost-codec",
  "test_storage/prost-codec",
  "tidb_query/prost-codec",
  "tikv/prost-codec",
  "tipb/prost-codec",
  "txn_types/prost-codec",
]

[dependencies]
futures = "0.1"
kvproto = { git = "https://github.com/pingcap/kvproto.git", branch = "release-4.0", default-features = false }
protobuf = "2"
test_storage = { path = "../test_storage" }
tidb_query = { path = "../tidb_query" }
tikv = { path = "../../", default-features = false }
tikv_util = { path = "../tikv_util" }
tipb = {git = "https://github.com/tidb-hackathon-2020-wasm-udf/tipb.git", branch = "wasm-udf-r4", default-features = false}
txn_types = { path = "../txn_types" }
